spdx/spdx-3-model

model/Core/Classes/Annotation.md, model/Core/Classes/Bom.md, model/Core/Classes/ExternalReference.md, model/Core/Classes/Hash.md, model/Core/Classes/Relationship.md, model/Core/Core.md, model/Core/Properties/algorithm.md, model/Core/Properties/annotationType.md, model/Core/Properties/completeness.md, model/Core/Properties/externalId.md, model/Core/Properties/externalReferenceType.md, model/Core/Properties/relationshipType.md, model/Core/Vocabularies/ActorType.md, model/Core/Vocabularies/AnnotationType.md, model/Core/Vocabularies/ExternalIdentifierType.md, model/Core/Vocabularies/ExternalReferenceType.md, model/Core/Vocabularies/HashAlgorithm.md, model/Core/Vocabularies/RelationshipCompleteness.md, model/Core/Vocabularies/RelationshipType.md, model/Software/Classes/File.md, model/Software/Classes/Package.md, model/Software/Classes/Sbom.md, model/Software/Classes/Snippet.md, model/Software/Properties/filePurpose.md, model/Software/Properties/packagePurpose.md, model/Software/Properties/snippetPurpose.md, model/Software/Software.md, model/Software/Vocabularies/SoftwarePurpose.md
Changes names according to tech team decisions,
as documented in Tech Meeting 2022-12-06.
=> Change naming

model/AI/AI.md
Add in the AI.md place holder for the profile.
- Signed-off-by: Kate Stewart <kate.stewart@att.net>
=> Create starting point for AI Profile

model/Core/Classes/Bundle.md, model/Core/Classes/ElementCollection.md, model/Core/Classes/NamespaceMap.md, model/Core/Classes/SpdxDocument.md, model/Core/Properties/context.md, model/Core/Properties/element.md, model/Core/Properties/externalId.md, model/Core/Properties/imports.md, model/Core/Properties/locationHint.md, model/Core/Properties/namespace.md, model/Core/Properties/namespaces.md, model/Core/Properties/prefix.md, model/Core/Properties/rootElement.md
=> add Collection related descriptions

.github/workflows/spec-parser.yml
- this clones and runs https://github.com/spdx/spec-parser/
- the generated files are uploaded as artifacts to the CI job
=> Add CI job to run spec-parser and upload its output

model/Core/Properties/completeness.md, model/Core/Properties/from.md, model/Core/Properties/relationshipType.md, model/Core/Properties/to.md, model/Core/Vocabularies/RelationshipCompleteness.md, model/Core/Vocabularies/RelationshipType.md
=> add Relationship related descriptions

model/Core/Classes/IntegrityMethod.md, model/Core/Properties/algorithm.md, model/Core/Properties/hashValue.md, model/Core/Properties/verifiedUsing.md, model/Core/Vocabularies/HashAlgorithm.md
=> add IntegrityMethod related descriptions

model/Licensing/Classes/ConjunctiveLicenseSet.md, model/Licensing/Classes/CopyrightTextField.md, model/Licensing/Classes/DisjunctiveLicenseSet.md, model/Licensing/Classes/License.md, model/Licensing/Licensing.md
There is a file missing in the licensing profile.
Ping @swinslow
=> fix some issues in markdowns in licensing branch

model/Dataset/Properties/sensitivePersonalInformation.md
supersedes #184, including all comments from that PR
=> Dataset profile: add sensitivePersonalInformation.md

model/Software/Classes/Package.md, model/Software/Properties/sourceInfo.md
=> Software profile: add sourceInfo

model/Dataset/Classes/Dataset.md, model/Dataset/Properties/datasetAvailability.md, model/Dataset/Vocabulary/DatasetAvailability.md, model/Dataset/Vocabulary/DatasetAvailabilityType.md
Adding the datasetAvailability property to the dataset profile
=> Add dataset Availability to dataset profile. 

model/Glossary.md
Signed-off-by: Nisha Kumar <nisha.kumar@oracle.com>
=> Add glossary of terms

serialization/README.md, serialization/canonical.md, serialization/cbor.md, serialization/json.md, serialization/rdf.md
- Adds initial files about serializarion
=> serialization

model/Core/Classes/ExternalIdentifier.md, model/Core/Properties/identifierLocator.md, model/Core/Properties/issuingAuthority.md
As decided in the 2023-04-25 Tech Team call.
Signed-off-by: Alexios Zavras (zvr) <github@zvr.gr>
=> Adds new properties in Core/ExternalIentifier

model/Core/Classes/SemVer.md
Signed-off-by: Alexios Zavras (zvr) <github@zvr.gr>
=> Adds pattern shape for SemVer strings

model/Licensing/Classes/License.md, model/Licensing/Classes/LicenseAddition.md, model/Licensing/Properties/standardAdditionTemplate.md, model/Licensing/Properties/standardLicenseTemplate.md
=> Licensing: Add standard template properties

model/Build/Classes/Build.md, model/Build/Properties/buildEnd.md, model/Build/Properties/buildStart.md, model/Core/Classes/Artifact.md, model/Core/Classes/CreationInfo.md, model/Core/Properties/builtTime.md, model/Core/Properties/created.md, model/Core/Properties/releaseTime.md, model/Core/Properties/validUntilTime.md
- Adds uses of new DateTime classs from core profile
=> Use new DateTime class

model/Licensing/Classes/CopyrightTextField.md
=> Licensing: Remove FIXME from CopyrightTextField

model/Core/Classes/Relationship.md, model/Core/Properties/endTime.md, model/Core/Properties/startTime.md
As was agreed in SPDX Technical Team Meeting of 2023-04-25.
=> Add start and end time to Relationships

model/Software/Classes/SoftwareArtifact.md
=> Licensing and Software: add Licensing properties to SoftwareArtifact

model/Software/Classes/File.md
I tried to use language consistent with the property names.
=> Add summary and desc. to File

model/Core/Vocabularies/RelationshipType.md
Replaced all TODO's with comments.
=> Add comments for relationships

Contributing.md
Per discussion on the outreach team
=> Update Contributing for review of the release candidate

Contributing.md
Updated the list of Profile Maintainers per discussion with @kestewart
=> Update Contributing.md adding Profile Maintainers

model/Core/Classes/ExternalMap.md, model/Core/Properties/definingDocument.md
=> Add definingDocument property

model/Core/Vocabularies/RelationshipType.md
Add in the relationships to summarize the training, testing and evidence to be used in AI and Dataset summarization.
Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>
=> Update RelationshipType.md to add in AI & Dataset useful relationships

serialization/README.md
Adds serialization use cases about licensing
=> licensing use cases for serialization

model/Core/Vocabularies/ExternalReferenceType.md
See individual commits for details
=> Add several new external references

model/Core/Classes/CreationInfo.md
=> make specVersion mandatory

model/Software/Classes/SoftwareArtifact.md
=> Change cardinality for attributionText to [0..*]

serialization/json.md
This an attempt at documenting how to parse JSON-LD without any RDF knowledge.
I'm not quite sure where to put this, though.
=> add documentation on how to parse JSON-LD as pure JSON

model/Core/Properties/dataLicense.md
Change non-ASCII quotes to ASCII ones, like all other instances.
=> Remove non-ASCII chars

model/Core/Vocabularies/RelationshipCompleteness.md
Clarifies the summary, description, and entries
=> add clarity to RelationshipCompleteness.md

.github/workflows/spec-parser.yml
It looks like I missed this in PR #502
=> Add the model.jsonld and context.json to the github.io pages

serialization/json_ld/examples/agent1.json, serialization/json_ld/examples/annotation1.json, serialization/json_ld/examples/converted_from_spdx_2.json, serialization/json_ld/examples/file1.json, serialization/json_ld/examples/org1.json, serialization/json_ld/examples/package1.json, serialization/json_ld/examples/person1.json, serialization/json_ld/examples/person2.json, serialization/json_ld/examples/person3.json, serialization/json_ld/examples/relationship1.json, serialization/json_ld/examples/sbom1.json, serialization/json_ld/examples/spdx_document1.json, serialization/json_ld/examples/spdx_document2.json, serialization/json_ld/examples/spdx_document3.json, serialization/json_ld/examples/spdx_document4.json, serialization/json_ld/examples/tool1.json, serialization/json_ld/examples/two_sboms.json
closes https://github.com/spdx/spdx-3-model/issues/540
=> fix context location in jsonld examples

.github/workflows/spec-parser.yml, .github/workflows/test_context.py
currently, the generated context.json file is not a valid context (at least the python library `rdflib` bails out). This adds a test to the pipeline to enforce its correctness. In the end this needs to be fixed in the spec parser.
<pre>
$ python .github/workflows/test_context.py /path/to/context.json
Traceback (most recent call last):
File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 18, in <module>
testLocalContext(sys.argv[1])
File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 13, in testLocalContext
parseString(data)
File "/tmp/tmp.gNYmijLEGg/spdx-3-model/.github/workflows/test_context.py", line 9, in parseString
return Graph().parse(data=data, format='json-ld')
File "/tmp/tmp.5ymDrNfyvh/venv/lib/python3.10/site-packages/rdflib/ …
=> json-ld context is currently invalid, add another check that validates the context for jsonld

model/AI/AI.md, model/AI/Classes/AIPackage.md, model/Dataset/Classes/Dataset.md, model/Dataset/Dataset.md
@kestewart I have added the constraints with my best interpretation of #462. Please review if this looks okay
=> Update AIPackage.md to express constraints

model/Core/Vocabularies/RelationshipType.md
Performs several cleanups to the relationship types per discussion with @kestewart 
Closes #550
=> Cleanup relationships

serialization/json-ld.md
Thanks for building this context file! It's great to have this--and seems useful already even with SPDX 2.x files.
Cheers!
:tophat:
=> Fix context URLs in JSON-LD docs

model/Lite/Lite.md
Due to write permissions, commit applied to forked repository
=> Updated Lite profile definition, to eliminate PackageUrl and added decs. for conformance to other profiles.

model/ExpandedLicensing/Classes/License.md, model/ExpandedLicensing/Classes/LicenseAddition.md
=> Add seeAlso property to License and LicenseAddition

model/Core/Classes/Annotation.md
Was discussed in tech call, during review of drawio.
=> fix cardinality of contentType in Annotation

model/Core/Classes/ElementCollection.md
=> Remove imports from ElementCollection

model/SimpleLicensing/SimpleLicensing.md
This replaces a "TODO" comment.
=> Update text for SimpleLicensing profile

model/Core/Properties/issuingAuthority.md
=> Add description to issuingAuthority property

.github/workflows/validate-pr.yml, model/Extension/Classes/Extension.md
Fixes issue where the markdown parser is failing
=> Remove empty properties heading

model/ExpandedLicensing/Classes/IndividualLicensingInfo.md
It looks like one of my previous PR's caused this failure.
=> Fix IndividualLicense -> IndividualLicensingInfo

model/Core/Properties/identifierLocator.md, model/Security/Properties/catalogType.md, model/Security/Properties/impactStatementTime.md, model/Security/Properties/statusNotes.md, model/Security/Properties/vexVersion.md
Adds summaries and descriptions to the remaining markdown files in #367
=> Close out TODOs from Issue 367

model/Core/Datatypes/MediaType.md
Fixes #569
This basically reverts the MediaType back to the definition before commit cd13828
=> Change MediaType to conform to RFC 2046

model/Core/Classes/PositiveIntegerRange.md, model/Core/Properties/beginIntegerRange.md, model/Core/Properties/endIntegerRange.md
=> rename begin and end to beginIntegerRange and endIntegerRange

model/ExpandedLicensing/Classes/WithAdditionOperator.md, model/ExpandedLicensing/Properties/subjectExtendableLicense.md, model/ExpandedLicensing/Properties/subjectLicense.md
=> Add a subjectExtendableLicense property

model/Core/Vocabularies/SupportType.md
Per discussion on the 19 March 2023 tech call, this pull requests adds an additional support type of deployed.
Related to issue #561
=> Add deployed support type

Glossary.md
- Sort terms A-Z
- Replace abbreviations like "json-ld", "xml" with "JSON-LD", "XML"
- Break few long paragraphs into smaller ones
- No change in content
=> Glossary.md: Sort terms alphabetically (A-Z)

model/AI/Properties/safetyRiskAssessment.md, model/AI/Vocabularies/SafetyRiskAssessmentType.md
Update to make it more explicit about the intention of the property and the intention of the assessment methodology.
- Rewrite the second paragraph of the description so the word "is intended" is clearly refer to the methodology, and not the property.
- The property is intended to "Records the results of general safety risk assessment of the AI system."
- The methodology (which we borrowed in) is intended to "assist authorities when they assess general product safety compliance."
See comment/suggestion by @rgopikrishnan91 and discussion in https://github.com/spdx/spdx-3-model/pull/675#issuecomment-2023787199
=> AI: Update safetyRiskAssessment description

model.drawio, model/AI/Classes/AIPackage.md
- Update AIPackage.md and model.drawio to reflects changes in #697
=> Change energyConsumption type to EnergyConsumption

model/Core/Properties/rootElement.md
=> root Element(s) of a tree of elements contained in a BOM (not SBOM)

model/AI/Properties/modelExplainability.md
"explain the model" -> "explain the results from the model"
This will fix #770 (3.0.1)
=> Update modelExplainability prop description

CHANGELOG.md
Note some changes that can be breaking or change model behavior
=> Update CHANGELOG 2024-08-10

model/Core/Properties/specVersion.md
Add this sentence to the description
"The patch version number shall be incremented when backward compatible bug fixes are made."
To fix #733
=> Add patch information for specVersion

model/Build/Properties/environment.md
=> Fix reference to parameter

CHANGELOG.md
=> Update CHANGELOG for `parameters` -> `parameter`

CHANGELOG.md, serialization/jsonld/examples/converted_from_spdx_2.json
@goneall If you're agree with this, you can merge this suggestions to #847 and we can review them together there.
Alternatively, I can close this one and open a new PR to merge this to main branch insstead. Thank you.
=> Add change log for `import` property rename + modify an example

scope.md
Fixes https://github.com/spdx/spdx-3-model/issues/873
=> To be consistent, copy scope.md file from spdx-spec to spdx-3-model

model/Licensing/Licensing.md
Option 3/3 to fix #916
Options:
- #920
- #921
- #922
**Only one of the three should be used**
=> Collapse a nested list to a single-level list to avoid rendering issue in MkDocs

model/Core/Properties/standardName.md
=> Fix grammar in standardName description

model/Security/Classes/VulnAssessmentRelationship.md, model/Security/Properties/assessedElement.md
See: https://github.com/spdx/spdx-3-model/issues/911
=> SoftwareArtifact as range for assessedElement
