- model/Core/Classes/ExternalIdentifier.md
So far, only `ExternalIdentifierType` exists in `Core/Vocabularies`, so I added `ExternalIdentifier` according to https://github.com/spdx/spdx-3-model/blob/main/model.png
Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>
> add ExternalIdentifier.md to Core/Classes

- .gitignore
- model/Licensing/Classes/ConjunctiveLicenseSet.md
- model/Licensing/Classes/CopyrightText.md
- model/Licensing/Classes/CopyrightTextField.md
- model/Licensing/Classes/CustomLicense.md
- model/Licensing/Classes/CustomLicenseException.md
- model/Licensing/Classes/DisjunctiveLicenseSet.md
- model/Licensing/Classes/License.md
- model/Licensing/Classes/LicenseException.md
- model/Licensing/Classes/LicenseExpression.md
- model/Licensing/Classes/LicenseField.md
- model/Licensing/Classes/ListedLicense.md
- model/Licensing/Classes/ListedLicenseException.md
- model/Licensing/Classes/NoAssertionLicense.md
- model/Licensing/Classes/NoAssertionText.md
- model/Licensing/Classes/NoneLicense.md
- model/Licensing/Classes/NoneText.md
- model/Licensing/Classes/OrLaterOperator.md
- model/Licensing/Classes/WithExceptionOperator.md
- model/Licensing/Properties/attributionText.md
- model/Licensing/Properties/concludedLicense.md
- model/Licensing/Properties/copyrightText.md
- model/Licensing/Properties/declaredLicense.md
- model/Licensing/Properties/licenseComment.md
See discussion in #65 -- this is a separate PR meant to merge the initial draft into the separate `licensing-profile` branch for further review, Issues and PRs.
> Initial draft of Licensing content for separate profile branch

- model/Core/Classes/Element.md
- model/Core/Classes/ExternalMap.md
- model/Core/Classes/ExternalReference.md
- model/Core/Classes/NamespaceMap.md
- model/Core/Properties/externalId.md
- model/Core/Properties/locationHint.md
- model/Core/Properties/locator.md
- model/Core/Properties/namespace.md
- model/Core/Properties/spdxId.md
- model/Software/Classes/File.md
- model/Software/Classes/Package.md
- model/Software/Classes/Snippet.md
- model/Software/Properties/contentIdentifier.md
- model/Software/Properties/downloadLocation.md
- model/Software/Properties/homePage.md
- model/Software/Properties/packageUrl.md
anyURI is part of the xml schema: https://www.w3.org/TR/xmlschema11-2/#anyURI
Therefore we should prepend it with the `xsd:` namespace.
> Add `xsd:` namespace to `anyURI`

- model/Software/Classes/Package.md
- model/Software/Classes/Snippet.md
these two properties were missed in the metadata of two files.
> add missing name properties to Package and Snippet

- model/Software/Classes/File.md
- model/Software/Classes/Package.md
- model/Software/Classes/Sbom.md
- model/Software/Classes/Snippet.md
- model/Software/Properties/byteRange.md
- model/Software/Properties/contentType.md
- model/Software/Properties/downloadLocation.md
- model/Software/Properties/filePurpose.md
- model/Software/Properties/homePage.md
- model/Software/Properties/lineRange.md
- model/Software/Properties/packagePurpose.md
- model/Software/Properties/snippetPurpose.md
- model/Software/Vocabularies/SoftwarePurpose.md
This is an attempt to fill in the missing descriptions in the Software profile. Where possible, I tried to copy from the SPDX-2.3 specification.
This misses descriptions for
- packageUrl
- contentIdentifier
- File
which I was not sure about their actual definition.
> add Software related descriptions

- model/Core/Classes/CreationInformation.md
As seen in the model.png.
This field will be needed to convert the SPDX2 property `CreatorComment` to SPDX3.
Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>
> Add `comment` property in CreationInformation.md

- model/Software/Classes/Package.md
- model/Software/Properties/packageVersion.md
As seen in the model.png.
This field will be needed to convert the SPDX2 property `PackageVersion` to SPDX3.
Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>
> add packageVersion property in Package.md

- model/Core/Properties/description.md
- model/Core/Properties/name.md
- model/Core/Properties/originatedBy.md
- model/Core/Properties/spdxId.md
- model/Core/Properties/summary.md
> add Element related descriptions

- model/Core/Classes/ExternalIdentifier.md
- model/Core/Classes/ExternalReference.md
- model/Core/Classes/MediaType.md
- model/Core/Properties/contentType.md
- model/Core/Properties/externalIdentifierType.md
- model/Core/Properties/externalIdentifiers.md
- model/Core/Properties/externalReferenceType.md
- model/Core/Properties/externalReferences.md
- model/Core/Properties/locator.md
- model/Core/Vocabularies/ExternalIdentifierType.md
- model/Core/Vocabularies/ExternalReferenceType.md
> add External ID/Ref related descriptions

- model/Core/Properties/annotationType.md
- model/Core/Properties/statement.md
- model/Core/Properties/subject.md
- model/Core/Vocabularies/AnnotationType.md
> add Annotation related descriptions

- model/Core/Classes/SpdxDocument.md
- model/Software/Classes/File.md
- model/Software/Classes/Package.md
- model/Software/Classes/Sbom.md
- model/Software/Classes/Snippet.md
Adds restrictions to external properties
The way to specify restrictions to external properties is:
- refer to the external property as a complete path of /{profile}/{class}/{property}
- add the shape defintion, which overwrites the original one.
Realistically, the restrictions will mostly be optional properties becoming mandatory,
i.e., minCount changing from 0 to 1.
> External properties restrictions

- model/Dataset/Classes/Dataset.md
- model/Dataset/Properties/sensors.md
The `sensors` property uses a key-value-style format, which is provided by the new `DictionaryEntry` class.
> Dataset profile: use DictionaryEntry for sensors property

- model/Licensing/Classes/ConjunctiveLicenseSet.md
- model/Licensing/Classes/DisjunctiveLicenseSet.md
- model/Licensing/Properties/member.md
Sets have members, not children.
> Renames the property of set member

- model/Licensing/Properties/comment.md
- model/Licensing/Properties/deprecatedVersion.md
- model/Licensing/Properties/example.md
- model/Licensing/Properties/isDeprecatedLicenseId.md
- model/Licensing/Properties/isFsfLibre.md
- model/Licensing/Properties/isOsiApproved.md
- model/Licensing/Properties/licenseId.md
- model/Licensing/Properties/licenseText.md
- model/Licensing/Properties/listVersionAdded.md
- model/Licensing/Properties/name.md
- model/Licensing/Properties/obsoletedBy.md
- model/Licensing/Properties/seeAlso.md
- model/Licensing/Properties/standardLicenseHeader.md
This adds the skeleton markdown files for the properties of the `License` class.
I noticed the following issue, already discussed in #167:
`name` and `comment` are already defined in Core. I suggest renaming them to `licenseName` and `licenseComment`. This in turn clashes with the already existing property `licenseComment`. The latter is not used (yet), and seems to only refer to concluded licenses, so I suggest renaming it to `concludedLicenseComment`.
> Add License properties

- model/Licensing/Classes/CustomLicense.md
- model/Licensing/Classes/License.md
- model/Licensing/Classes/ListedLicense.md
- model/Licensing/Classes/NoAssertionLicense.md
- model/Licensing/Classes/NoAssertionText.md
- model/Licensing/Classes/NoneLicense.md
- model/Licensing/Classes/NoneText.md
- model/Licensing/Licensing.md
This change removes several of the TBDs, which have been moved out into separate issue threads at:
* https://github.com/spdx/spdx-3-model/issues/204
* https://github.com/spdx/spdx-3-model/issues/205
> Licensing: cleanup of TBDs and add summary text

- model/Build/Classes/Build.md
- model/Dataset/Classes/Dataset.md
This adds a few missing spaces so that the automated spec-parser can parse the files.
> add spaces for parsing compatibility

- model/AI/Classes/AIPackage.md
- model/AI/Properties/hyperparameters.md
- model/AI/Properties/metrics.md
- model/AI/Properties/metricsDecisionThresholds.md
The AI profile uses some key-value-like properties that can make use of the structure provided by the new `DictionaryEntry` class.
> AI profile: use DictionaryEntry where appropriate

- model/Core/Classes/Artifact.md
- model/Core/Properties/builtTime.md
- model/Core/Properties/releaseTime.md
- model/Core/Properties/validUntilTime.md
These entries not only ensure compatibility with 2.3 but can also be used by other profiles like dataset.
> add builtTime, releaseTime and validUntilTime to Artifact

- model/Core/Classes/IntegrityMethod.md
IntegrityMethod is used for integrity, not identification.  We have identification classes for that purpose (e.g. `packageUrl`, `externalIdentifiers`).
> Propose changing "identification" to "verification"

- model/Core/Classes/PositiveIntegerRange.md
- model/Core/Properties/begin.md
- model/Core/Properties/end.md
- model/Software/Classes/Snippet.md
I noticed that the `PositiveIntegerRange` class and its properties were not yet defined in markdown.
`PositiveIntegerRange` is currently only used in the Software namespace in the properties `byteRange` and `lineRange` of the `Snippet` class, but I think it is safer to include it in the Core namespace to enable future extensions to make use of it.
> Core: add PositiveIntegerRange class

- model/Core/Classes/Element.md
- model/Core/Properties/extension.md
- model/Core/Properties/externalIdentifier.md
- model/Core/Properties/externalReference.md
According to https://github.com/spdx/spdx-3-model/issues/226, property names should be kept singular. I changed this for Core.
Two issues remain:
- There are both `namespace` and `namespaces`. Maybe we can find a better word for the latter as it is actually a `namespaceMap`?
- `imports` would become `import`, which would be a keyword in many programming languages, for example in Python. That is not a good idea. As this is an external map, maybe `importMap` might be an idea?
> Core: Use singular for properties

- model/Build/Classes/Build.md
- model/Build/Properties/environment.md
- model/Build/Properties/parameters.md
This replaces the key-value-like property types with the new DictionaryEntry class.
> Build profile: use DictionaryEntry class for maps

- model/Build/Classes/Build.md
- model/Build/Properties/configSourceDigest.md
As is used for example [here](https://github.com/spdx/spdx-3-model/blob/main/model/Software/Classes/Package.md).
> Build profile: use slash notation to reference classes from Core

- model/Dataset/Classes/Dataset.md
I fixed two property names to match the ones in the Properties folder.
Also added `maxCount: 1` to both as it does not make sense to have multiple values for `sensitivePersonalInformation` (a boolean) or `confidentialityLevel`.
> Dataset: fix names and cardinalities

- model/Core/Classes/LifecycleScopedRelationship.md
- model/Core/Vocabularies/LifecycleScopeType.md
- model/Core/Vocabularies/RelationshipCompleteness.md
- model/Software/Classes/SoftwareDependencyRelationship.md
- model/Software/Vocabularies/DependencyConditionalityType.md
- model/Software/Vocabularies/SoftwareDependencyLinkType.md
also add the three software dependency vocabularies `DependencyLinkType`, `DependencyRequirement` and `DependencyScope` according to https://github.com/spdx/spdx-3-model/blob/main/model.png
Signed-off-by: Armin Tänzer <armin.taenzer@tngtech.com>
> add SoftwareDependencyRelationship and LifecycleScopedRelationship

- model/Core/Properties/identifier.md
The markdown file for the identifier property was still missing in core.
> Add identifier property

- model/Core/Classes/Relationship.md
According to the png relationshipType is mandatory.
> Fix cardinality of relationshipType

- model/Core/Classes/DateTime.md
The type might as well be called `Timestamp`,
but `DateTime` is already well-known from xsd.
Closes #215
Signed-off-by: Alexios Zavras (zvr) <github@zvr.gr>
> Adds DateTime data type in Core

- model/Core/Vocabularies/RelationshipType.md
This PR adds the new relationship types required by the security profile.
The first commit adds the VEX relationship types required by `VulnerabilityVexAssessmentRelationship`:
- affected
- notAffected
- fixed
- underInvestigation
**HOLD** until the final Security profile is in 
/cc @tsteenbe @rnjudge @jeff-schutt @karsten-klein @goneall
> Security Profile: Add Relationship Types

- model/Core/Vocabularies/RelationshipType.md
This commit modifies the proposed VEX relationships to make them all work in the same direction: from vulnerability to (VEX) product addressing [feedback from the tech call on May 2 2023](https://github.com/spdx/spdx-3-model/pull/248#issuecomment-1531761847).
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
> Update VEX relationships to even their directions and add prepositions

- Glossary.md
This commit adds a definition of _agent_ to the glossary (trying my best to capture Sean's definition)
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
> Add "Agent" entry to Glossary.md

- model/Core/Vocabularies/RelationshipType.md
This commit adds relationship types for the Security profile that may
be used to associate security-related elements or agents. The
definitions for these types were agreed upon at the May 3rd
Defects call.
cc @puerco @tsteenbe @jeff-schutt @kestewart
> Add preliminary Security Relationship Types

- model/Core/Vocabularies/ExternalReferenceType.md
Update the `securityAdvisory`, `securityFix`, and `securityOther` external reference type definitions based on discussion in the defects working group call on May 3rd.
> Update security externalReferenceType descriptions

- model/Core/Vocabularies/ExternalReferenceType.md
Provide SPDX creators an option to easily share any (raw) info collected which may be useful or can be clean-up by downstream users.
Relates-to: #251
> Add new types to ExternalReferenceType

- model/Licensing/Classes/AnyLicenseInfo.md
- model/Licensing/Classes/ConjunctiveLicenseSet.md
- model/Licensing/Classes/DisjunctiveLicenseSet.md
- model/Licensing/Classes/License.md
- model/Licensing/Classes/OrLaterOperator.md
- model/Licensing/Classes/WithExceptionOperator.md
- model/Licensing/Properties/member.md
> Licensing: Rename LicenseExpression to AnyLicenseInfo

- model/Core/Classes/Element.md
Made CreationInfo optional to prevent SBOM bloating see for example https://gist.github.com/meretp/561e4ea963122f5811a147ea056e4d84#file-example-jsonld-L29-L75. CreationInfo should only be mandatory on certain elements such as SPDXDocument, Bundle, etc. 
IMO SPDX should enable linked data format such as JSON-LD and RDF but it must not make it mandatory for JSON and YAML formats. Often heard complaint about SPDX 2.x was that it was too complex/bloated, we should not make the same mistake in SPDX 3.0 but providing something simple for those that just want to exchange data and enable linked data SBOM for parties that want to graph reasoning.
Ping @maxhbr  @jeff-schutt  @puerco - please add your opinion from our discussions here as well.
> Fixup various Element properties

- model/AI/AI.md
- model/Build/Build.md
- model/Core/Core.md
- model/Dataset/Dataset.md
- model/Software/Software.md
This changes the ids in the root md files to the convention used in the generated spec and adds a `Dataset.md`.
> change # to / and add root .md for dataset profile

- model/Build/Classes/Build.md
- model/Build/Properties/buildEndTime.md
- model/Build/Properties/buildStartTime.md
Most time related fields in the spec end with Time.
> Add Time to build time properties for consistency

- model/Software/Properties/copyrightText.md
> Licensing: Clarify as strings for NONE and NOASSERTION

- model/Security/Classes/VexAffectedVulnAssessmentRelationship.md
- model/Security/Classes/VexFixedVulnAssessmentRelationship.md
- model/Security/Classes/VexNotAffectedVulnAssessmentRelationship.md
- model/Security/Classes/VexUnderInvestigationVulnAssessmentRelationship.md
The property relationshipType is defined in the ancestor class core/Relationship and does not need to be repeated in the sub-classes.
> Remove relationshipType from subclasses

- model/Security/Classes/VulnAssessmentRelationship.md
- model/Security/Properties/withdrawnTime.md
Looking at the generated documentation fro the model, I noticed that the property `security:withdrawn` isn't assigned correctly. This was caused by the wrong title in the markdown file for `withdrawnTime`.
The `to` property for `Relationship` is optional since #293. From the descriptions in the security relationships I think the `to` property should be mandatory for all security relationships.
> Security: Fix markdown and add external property restriction for "to"

- model/Software/Properties/concludedLicense.md
- model/Software/Properties/declaredLicense.md
Working with the `spec-parser` and the generated model.ttl file I noticed these incorrect references.
> fix references to LicenseField

- model/Core/Vocabularies/ExternalIdentifierType.md
This adds cve and securityOther entries as ExternalIdentifierType(s) to be consistent with the current security model[1]
[1]https://raw.githubusercontent.com/spdx/spdx-3-model/main/model-security-profile.png
Resolves #316
> Add cve & securityOther as ExternalIdentifierType

- model/Core/Vocabularies/RelationshipType.md
- model/Security/Classes/CvssV2VulnAssessmentRelationship.md
- model/Security/Classes/CvssV3VulnAssessmentRelationship.md
- model/Security/Classes/EpssVulnAssessmentRelationship.md
- model/Security/Classes/ExploitCatalogVulnAssessmentRelationship.md
- model/Security/Classes/SsvcVulnAssessmentRelationship.md
As discussed in https://github.com/spdx/spdx-3-model/issues/331 we are considering simplifying the security relationships to a single `hasAssessmentFor`.
This PR removes the following relationship types and updates the markdowns to use `hasAssessmentFor` while introducing it into the core vocabulary:
- hasCvssV2AssessmentFor
- hasCvssV3AssessmentFor
- hasEpssAssessmentFor
- hasExploitCatalogAssessmentFor
- hasSsvcAssessmentFor
/cc @tsteenbe @rnjudge @jeff-schutt
closes #331
> Security: Simplify assessment relationships

- serialization/json.md
- serialization/json_ld/examples/package.jsonld
- serialization/json_ld/examples/person.jsonld
- serialization/json_ld/examples/spdx_document.jsonld
As there seems to be some confusion around how json-ld would actually look like, this is an attempt to provide a place for examples on which further discussions can be based.
I'm not sure where the most interest lies, so please tell me which use cases you would like to see further examples on! :)
Validation of json-ld would be performed against a separate SHACL file generated from the specification. This will be automatically added and kept up-to-date once #344 is merged.
Work is also underway to generate a json-schema that will validate json-ld output.
There is still the hope that the json-ld serialization works fine for everyone so that we don't have to invent a separate json (non-json-ld) serialization. If you have any concerns about this, please speak up!
(For clarification: A "json …
> Add json-ld serialization examples

- serialization/README.md
As discussed in today's serialization meeting, it will be helpful to have a list of use cases that elucidate how serializations will work in action. Examples for these use cases will be included in sub-directories of the different serialization formats.
The current list is only concerned with `Core` and `Software`.
We would be happy if other profiles could contribute use cases they have been or still are struggling with.
> add list of serialization use cases

- model/Dataset/Classes/Dataset.md
- model/Dataset/Properties/datasetType.md
- model/Dataset/Vocabularies/DatasetType.md
Closes #363 
This PR introduces a new vocabulary that can be used to describe types of a dataset in a concrete way. Now, instead of a string to describe a `datasetType`, users can choose from the selection for the type(s) that describe their dataset, making it easier for tools to generate and parse standardized dataset types. See #363 for how we got this list of types. Of course users can always specify "Other" if their type isn't included, or "noAssertion" if they don't know the type. I tried to include real-life examples for each entry, but am open to other suggestions for examples!
> Added dataset types vocabulary

- model/AI/Classes/AIPackage.md
- model/Dataset/Classes/Dataset.md
Small fix as `purpose` is now split into `primaryPurpose` and `additionalPurpose`. I changed the reference to the former as having only `additionalPurpose` mandatory wouldn't make much sense to me.
> Change `purpose` references to `primaryPurpose`

- .github/workflows/spec-parser.yml
With this PR the GitHub Action is updated to automatically generate the html documentation and push the documentation (as multi-page and one-page document) as well as the generated `model.ttl` to the `gh-pages` branch. According to #140 the model.ttl should be pushed to a `generated` branch. To keep things simple I suggest to put everything that is automatically generated in the gh-pages branch, if you disagree I can adapt the PR to only push the generated documentation and we can add another workflow to push the `model.ttl` in another PR.
There is one open PR in the `spec-parser` to be able to fill the `Usage` table for each class with the corresponding properties. (https://github.com/spdx/spec-parser/pull/52). As this is already done in the documentation available via the `gh-pages` …
> Automatically generate the Ontospy documentation

- model/Licensing/Classes/LicenseExpression.md
This was a copy/paste error from a previous PR.  The name property should be `LicenseExpression` consistent with the header and file name.
Fixes #391
> Correct name property of LicenseExpression

- model/Software/Classes/Sbom.md
- model/Software/Properties/sbomType.md
- model/Software/Vocabularies/SbomType.md
Use PascalCase for consistency with every other name in the model.
> Change SBOMType to SbomType

- model/Core/Classes/Element.md
PR #273 was merged into the model without significant discussion at either the tech team or serialization subteam, and with a rationale that needs to be validated.
Since the beginning of SPDX v3 we have designed the model without in-depth discussion of serialization, leading to an implicit assumption that the model is serialization-independent.  273 violates that assumption, so now we need discuss and agree on what the model represents: 
1) Elements after they have been read into an application, or
2) Elements before they have been read into an application
The model diagram shows that every element must have creationInfo:
which represents the "meaning" of Element - no element can exist unless it has been created, and every application must be able to know the creationInfo of every Element …
> Mandatory creationInfo

- model/Core/Classes/CreationInfo.md
According to [this comment](https://github.com/spdx/spdx-3-model/issues/393#issuecomment-1602463064), the default for `maxCount` is `*`. This means that `specVersion`, `created` and `dataLicense` in the `CreationInfo` class do not have the right multiplicity, as there can't be more than one of these.
> set `maxCount: 1` for specVersion, created and dataLicense

- model/Core/Datatypes/DateTime.md
- model/Core/Datatypes/MediaType.md
- model/Core/Datatypes/SemVer.md
As discussed during the serialization meeting on July 14, this defines the three "string properties with formatting" as separate datatypes by moving them into a new folder "Datatypes" under Core.
> move DateTime, SemVer and MediaType to Datatypes directory

- model/Core/Classes/SpdxDocument.md
This only served to set `minCount: 1`, which is already handled by the "External properties restrictions" section.
> Remove redefinition of `name` property in `SpdxDocument`

- serialization/json_ld/examples/agent1.json
- serialization/json_ld/examples/annotation1.json
- serialization/json_ld/examples/converted_from_spdx_2.json
- serialization/json_ld/examples/file1.json
- serialization/json_ld/examples/org1.json
- serialization/json_ld/examples/package1.json
- serialization/json_ld/examples/person1.json
- serialization/json_ld/examples/person2.json
- serialization/json_ld/examples/relationship1.json
- serialization/json_ld/examples/sbom1.json
- serialization/json_ld/examples/spdx_document1.json
- serialization/json_ld/examples/spdx_document2.json
- serialization/json_ld/examples/spdx_document3.json
- serialization/json_ld/examples/spdx_document4.json
- serialization/json_ld/examples/tool1.json
- serialization/json_ld/examples/two_sboms.json
CreationInfo has been made mandatory again in #401, so the examples have to be updated.
This uses the de-duplication method of extracting the CreationInfo as a blank node.
> add CreationInfo to all Elements in json-ld examples

- serialization/README.md
As requested by the serialization team in the 2023-06-06 tech team meeting (see lines 69-76 of https://github.com/spdx/meetings/pull/347/files).
cc: @zvr @rnjudge @tsteenbe
> Adds serialization security use cases and improves formatting

- model/Core/Classes/CreationInfo.md
`created` and `dataLicense` are required, as described in Issue #393.  Partially fixed by PR #420.  This finishes the fix.
> creation info required fields

- model/Core/Classes/Element.md
- model/Core/Classes/ExternalRef.md
- model/Core/Properties/externalRef.md
- model/Core/Properties/externalRefType.md
- model/Core/Vocabularies/ExternalRefType.md
- model/Security/Classes/CvssV2VulnAssessmentRelationship.md
- model/Security/Classes/CvssV3VulnAssessmentRelationship.md
- model/Security/Classes/Vulnerability.md
Resolves #234
Fixes an unnecessary incompatibility between SPDX 2.3 and SPDX 3.0 spec versions.
> Rename ExternalReference to ExternalRef

- model/ExpandedLicensing/Properties/isFsfLibre.md
- model/ExpandedLicensing/Properties/isOsiApproved.md
> Update definitions of isFsfLibre and isOsiApprovied values

- model/ExpandedLicensing/Classes/License.md
- model/ExpandedLicensing/Classes/LicenseAddition.md
- model/ExpandedLicensing/Properties/licenseXml.md
> Add licenseXml property to License and LicenseAddition

- model/Core/Classes/Artifact.md
An Artifact's `suppliedBy` property has a cardinality of [0..1]. This was decided on at the March 21, 2023 tech call [1]. This PR indicates this cardinality by adding a maxCount to the property which was previously missing.
[1]https://github.com/spdx/meetings/blob/main/tech/2023-03-21.md#supplier-property
Resolves #437
> Indicate maxCount for Artifact's `suppliedBy`

- model/SimpleLicensing/Classes/LicenseExpression.md
- model/SimpleLicensing/Properties/customIdToUri.md
Fixes #380
Implements suggestion made in [this comment](https://github.com/spdx/spdx-3-model/issues/380#issuecomment-1620559842).
See [this comment](https://github.com/spdx/spdx-3-model/issues/380#issuecomment-1636183121) for an example serialization in JSON.
> Add customIdToUri Map to LicenseExpression

- model/SimpleLicensing/Classes/LicenseExpression.md
- model/SimpleLicensing/Properties/licenseListVersion.md
Fixes #131
This adds the `licenseListVersion` which in 2.3 was at the document level to the `licenseExpression`.
This is alternative solution to PR #480
> Add licenseListVersion to LicenseExpression

- model/Core/Classes/ExternalRef.md
- model/Core/Properties/locator.md
Partial fix for issue #81
Unlike an `ExternalIdentifier,` the `ExternalRef` locator string does not have a uniqueness requirement and the specific format depends on the  `externalRefType`.
Note that `ExternalIdentifier` already uses a separate property `identifierLocator` which remains of type `xsd:anyURI`
For the type "other", we should allow more arbitrary formats and not constrain it to a URI format.
> Change ExternalRef locator to be of type xsd:string

- model/Core/Vocabularies/ExternalRefType.md
> Add missing SPDX2 external reference types

- model/Core/Classes/ElementCollection.md
- model/Core/Classes/NamespaceMap.md
- model/Core/Classes/X-Collection.md
This is an attempt to implement the proposal documented in issue #489 as a pull request on top of pull request #490 
I took the approach of a pull request on top of the alternative pull request since the structure is basically the same.  It is just the descriptions which are different.
Note that the basic structure is also the same as pull request #403 - the main difference being the names of the properties and classes.
> Attempt to implement alternative proposal for namespaceMap

- model/Security/Classes/CvssV4VulnAssessmentRelationship.md
- model/Security/Properties/severity.md
- model/Security/Vocabularies/CvssSeverityType.md
Initial draft of changes to support CVSS version 4
CC: @rnjudge @tsteenbe @goneall
> add CvssV4VulnAssessmentRelationship.md and CvssSeverityType.md

- model/Security/Classes/CvssV2VulnAssessmentRelationship.md
In working to resolve https://github.com/spdx/spdx-3-model/pull/501#pullrequestreview-1651152833 I noticed that the [CVSS version 2.0 schema](https://www.first.org/cvss/cvss-v2.0.json) does not include a severity property. The changes remove this field from the class.
CC: @goneall @rnjudge @tsteenbe
> remove severity property from CvssV2VulnAssessmentRelationship.md

- model/AI/AI.md
- model/Core/Classes/Agent.md
- model/Core/Classes/Artifact.md
- model/Core/Classes/Bom.md
- model/Core/Classes/ExternalIdentifier.md
- model/Core/Classes/ExternalMap.md
- model/Core/Classes/LifecycleScopedRelationship.md
- model/Core/Classes/Organization.md
- model/Core/Classes/Person.md
- model/Core/Classes/Relationship.md
- model/Core/Classes/SoftwareAgent.md
- model/Core/Classes/Tool.md
- model/Core/Vocabularies/ExternalRefType.md
- model/Dataset/Properties/sensor.md
- model/Dataset/Vocabularies/ConfidentialityLevelType.md
- model/Dataset/Vocabularies/DatasetAvailabilityType.md
- model/ExpandedLicensing/Classes/CustomLicense.md
- model/ExpandedLicensing/Classes/CustomLicenseAddition.md
- model/ExpandedLicensing/Classes/ExtendableLicense.md
- model/ExpandedLicensing/Properties/licenseXml.md
- model/Security/Classes/VexFixedVulnAssessmentRelationship.md
- model/Security/Classes/VexUnderInvestigationVulnAssessmentRelationship.md
- model/Security/Vocabularies/CvssSeverityType.md
- model/SimpleLicensing/Classes/AnyLicenseInfo.md
- model/Software/Classes/SoftwareDependencyRelationship.md
This fixes various issues that the (new) spec-parser points out.
Among them:
- mismatches between "name" property and file name and title
- vocabularies entries not in lowerCamelCase
- missing sections ("Summary" in most/all cases)
- empty sections ("Properties" in most/all cases)
- ... and probably some others I don't remember
> Fixing typos/syntax errors

- model/Core/Properties/rootElement.md
- model/Core/Vocabularies/RelationshipType.md
Fixes #495 
This is a proposed solution based on the discussion in the tech call on 3 October, 2023.
> Replace describes relationship with rootElement property

- model/Core/Classes/ExternalMap.md
- model/Core/Properties/definingDocument.md
- model/Core/Vocabularies/RelationshipType.md
Per the decision in the serialization team, change the type of the definingDocument to Artifact and create a relationshipType to link the definingDocument to the SpdxDocument
> Update ExternalMap and relationships to reference Artifacts

- model/Core/Classes/ExternalMap.md
- model/Core/Properties/externalSpdxId.md
Implements the decision in the tech call on 17 October 2023 to reduce confusion between the `externalId` and `externalIdentifier` properties.
This pull request replaces https://github.com/spdx/spdx-3-model/pull/492
> Rename externalId to externalSpdxId

- model/Software/Vocabularies/SoftwarePurpose.md
These purposes are useful when dealing with images designed to be run on hardware or a VM, and aren't really covered by any of existing purposes
> Add diskImage and filesystemImage SoftwarePurpose

- model/Software/Vocabularies/SoftwarePurpose.md
This commit adds two new software purposes: `deviceDriver` and `platform` to keep the compatibility of this field with the recent CycloneDX 1.5 release.
/cc @kestewart @rnjudge @JPEWdev
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
> Add missing software purposes for CDX 1.5 compat

- model/Core/Classes/ElementCollection.md
As discussed in #526, an ElementCollection have 0 Elements is useful to prevent parties that are exchanging SPDX content from needing to have an out-of-band mechanism to indicate the case where there are no elements to be transferred.
Closes #526
Closes #551
> Allow ElementCollection to have 0 elements

- model/Licensing/Licensing.md
Fixed a couple missing words or other such clarifications.
Re-wrote the Summary to be less definitive regarding license compliance
Signed-off-by: Jilayne Lovejoy
> Update Licensing.md: minor wording updates

- model.drawio
- ExternalMap / locationHint: `anyUR[0..1]` -> `anyURI[0..1]` [1 instance]
- Element: `extension:Extension[0..1]` -> `extension: Extension[0..1]` (add a space delimiter between the property name and the type, for consistency with others) [4 instances]
> Fix a typo in model.drawio: anyUR[] -> anyURI[]

- model/Core/Vocabularies/ExternalIdentifierType.md
Updates the description of `swhid` as an entry in the vocabulary `Core/ExternalIdentifierType`
> Update SWHID description

- serialization/rdf.md
This simply updates the documentation on RDF,
to correctly match the IRIs used in the model,
as present in each namespace file.
> Updating the IRIs used in RDF

- .github/workflows/validate-pr.yml
Adds an action to validate proposed PRs by using the new spec-parser
Presumably the previous workflow can be deleted, but this is not done here.
> Validating PRs via new parser

- model/Core/Vocabularies/HashAlgorithm.md
The hash algorithms have only "TODO" for comments. I could not find any record of these in the minutes and no one has volunteered to fill in the description, so this PR deletes these algorithms from the model.
If anyone would like to add them back, please add them with a description as a separate pull request.
> Remove hash algorithms with no description

- model/Core/Vocabularies/RelationshipType.md
In practice, the definition of the delegatedTo relationship was flawed. Since it linked one agent to another, it was impossible to determine which delegatedTo relationships applied to which invokedBy relationships.
To solve this, reword the delegatedTo relationship to indicated that the `to` end must point to the specific invokedBy relationships to which it applies.
> Fix delegatedTo Relationship

- model/Core/Classes/ExternalIdentifier.md
- model/Core/Properties/issuingAuthority.md
> Change range of issueingAuthority from anyURI to string

- model/ExpandedLicensing/Properties/subjectLicense.md
> Change range of subjectLicense to ExtendableLicense

- model/Core/Classes/Artifact.md
- model/Core/Properties/supportLevel
- model/Core/Vocabularies/SupportType.md
The support available for a software artifact is a factor increasingly being used in risk assessment.  equirement of listing the support type available.   This set of enumerations has been based on the enumerations in ["Managing Legacy Technology Security (HIC-MaLTS)" from the Healthcare & Public Health Sector Coordinating Councils](https://healthsectorcouncil.org/wp-content/uploads/2023/03/Health-Industry-Cybersecurity-Managing-Legacy-Technology-Security-HIC-MaLTS.pdf), with additional categories being added after discussion with the AI & Data profile working groups.   It can be applied to software components, AI/ML trained models and datasets; in the medical industry as well as other industries. 
Signed-off-by: Kate Stewart <kstewart@linuxfoundation.org>
> Create Support Level to associate different types of support with an artifact. 

- model/Software/Classes/File.md
- model/Software/Properties/isDirectory.md
> Allow for File objects to describe directories

- model/Software/Classes/PackageVerificationCode.md
This pull request adds a legacy package verification code.
Based on the PackageVerificationCode as part of the security profile team call on 12 Jan 2023, we agreed that the model itself support package verification as is as long as we have additional documentation.  We decided to postpone the decision on how to handle the legacy package verification codes until after RC2.
This PR is a placeholder for possible inclusion if we decide to add the legacy support.
> Add legacy PackageVerificationCode as an integrity method

- model/Core/Classes/PackageVerificationCode.md
This change moves the PackageVerificationCode.md to the Core Class.
PackageVerificationCode is a Subclassof: model/Core/IntegrityMethod, which, (as with all Non-Element Classes) is a class defined in model/Core/Classes rather than model/Software/Classes
> moves PVC to core class

- model/Core/Classes/Artifact.md
- model/Core/Properties/standardName.md
This PR implements the consensus decision of the Feb 06, 2024 Tech call to  address immediate concerns under Issue #387.
More structured approaches to fully resolving Issue #387 will be pursued post RC2.
> Change name of 'standard' property to be 'standardName'

- model/ExpandedLicensing/Individuals/NoAssertionLicense.md
- model/ExpandedLicensing/Individuals/NoneLicense.md
This adds specific IRIs to the individuals in the licensing domain.
This is following up on https://github.com/spdx/spdx-3-model/pull/588#issuecomment-1917924971.
Please note that every class, property, individual, etc. already has an IRI (automatically generated, present in the generated files). The addition of explicit IRIs for Individuals allows us to choose custom ones, which are simpler.
> Adds IRIs to individual licenses

- model/Core/Properties/packageVerificationCodeExcludedFile.md
> Add missing packageVerificationCodeExcludedFile property

- model/Core/Properties/supportLevel.md
- model/Dataset/Properties/datasetAvailability.md
- model/Dataset/Properties/datasetType.md
- model/Security/Properties/severity.md
ObjectProperty must be used for vocabularies instead of DataProperty
> model: Fix several properties to use ObjectProperty instead of DataProperty

- model/Core/Datatypes/DateTime.md
Inherit from xsd:dateTime instead of xsd:string. The XSD definition is compatible with the SPDX definition, and this will allow code generation tools to map the value to a code-native datatype.
> model: Core: DateTime: Inherit from xsd:dateTime

- model/AI/Properties/safetyRiskAssessment.md
- model/AI/Vocabularies/SafetyRiskAssessmentType.md
Change description text for risk categories to refer to EU General Risk Assessment Methodology, not EU AI Act - as agreed in SPDX AI Team Meeting 2024-03-20.
See more analysis and discussions in #650.
> [3.0] AI: Update safetyRiskAssessment property desc to refer to general risk assessment

- model/Core/Properties/to.md
Min 0 allows producers to indicate that there are no known relationships of the given type.
Signed-off-by:  Kate Stewart <kstewart@linuxfoundation.org>
> Update to.md to reflect what min:0 means

- model/Software/Properties/copyrightText.md
This PR just clarifies that an "empty" copyrightText string should be interpreted as equivalent to `NOASSERTION`.
Fixes #655 
> Clarify meaning of empty copyrightText string

- model/Service/Classes/SoftwareService.md
- model/Service/Properties/serverAuthenticationProtocol.md
- model/Service/Vocabularies/AuthenticationProtocolType.md
Use case 9: Trust the identity of the service provider (authentication) Property and vocabulary added per the discussion on the software as a service call on 11 March, 2024
> Update service profile for use case 9

- model/SimpleLicensing/Classes/LicenseExpression.md
- model/SimpleLicensing/Properties/customIdToUri.md
- model/SimpleLicensing/Properties/licenseExpression.md
- model/SimpleLicensing/SimpleLicensing.md
The primary change in this commit is to reference the SPDX License Expressions annex (currently Annex D) in the LicenseExpression- related class and property definitions.
This is to avoid repeated text, and also to make it clear that license expression strings must conform to the license expression syntax in order to be valid.
This commit also fixes a couple of minor typos in the prior descriptions in SimpleLicensing.
Fixes #440 
Fixes #445
> Reference License Expressions annex and cleanup

- model/AI/Classes/AIPackage.md
- model/Dataset/Classes/DatasetPackage.md
@kestewart @sbarnum I have tried to address the issue #702 in this PR, can you guys please review it?
> To address #702 and explicitly state maxCount constraints on properties borrowed from other profiles

- model/Core/Vocabularies/ExternalRefType.md
- CISA Secure Software Development Attestation Form
- Update URL: https://www.cisa.gov/sites/default/files/2023-04/secure-software-self-attestation_common-form_508.pdf -> https://www.cisa.gov/resources-tools/resources/secure-software-development-attestation-form
- The current URL points to a draft version. The new URL is the final version.
- NIST SP 800-218
- Update URL: https://csrc.nist.gov/publications/detail/sp/800-218/final -> https://csrc.nist.gov/pubs/sp/800/218/final
- Update text label: "Secure Software Development Framework (SSDF)" -> "Secure Software Development Framework (SSDF) Version 1.1"
- NIST SP 800-161
- Update URL: https://csrc.nist.gov/publications/detail/sp/800-161/rev-1/final -> https://csrc.nist.gov/pubs/sp/800/161/r1/final
- NTIA VEX one-page summary
- Update text …
> Update URL to final version of docs in ExternalRefType.md

- model/Security/Classes/Vulnerability.md
- model/Security/Properties/vexVersion.md
This PR fixes two small Security profile issues that were discovered on the April 10th call.
See https://github.com/spdx/spdx-3-model/pull/649
> Small Security profile corrections

- model/Core/Classes/ExternalIdentifier.md
- model/Core/Classes/ExternalRef.md
This commit attempts to clarify the differences between ExternalIdentifier and ExternalRef classes.
Closes #705
> Clarify ExternalIdentifier and ExternalRef

- model/Core/Vocabularies/ExternalRefType.md
Per discussion in the April 10 Security call, this commit adds cwe (common weakness enumeration) as an ExternalIdentifierType.
Closes https://github.com/spdx/spdx-spec/issues/102
> Add cwe as ExternalRefType

- model/Security/Classes/Vulnerability.md
Update the Vulnerability class syntax example to change the externalIdentifierType from securityOther to securityAdvisory for a GitHub advisory because it references a well known advisory source.
Thanks @puerco for catching this.
> Change security externalIdentifierType in example

- model/Core/Classes/PackageVerificationCode.md
Updates the description of PackageVerificationCode to reference the contentIdentifier property which replaced the gitoid property.
> Change gitoid to contentIdentifier in PackageVerificationCode

- serialization/json-ld.md
- https://spdx.github.io/spdx-3-model/context.json -> https://spdx.org/rdf/3.0.0/spdx-context.jsonld
- https://github.com/spdx/spdx-3-model/blob/gh-pages/model.ttl -> https://spdx.org/rdf/3.0.0/spdx-model.ttl
- All breaks long lines to shorter ones
New IRIs according to [Tech meeting 2024-04-02](https://github.com/spdx/meetings/blob/main/tech/2024-04-02.md)
> Doc: Update IRI of JSON-LD context file in json-ld.md

- .editorconfig
- .gitattributes
Copying configurations from `spdx/spdx-spec` repo (sorted):
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/.editorconfig
- https://github.com/spdx/spdx-spec/blob/development/v3.0.1/.gitattributes
> Add .editorconfig and .gitattributes to enforce newline and whitespace consistency

- model/Licensing/Licensing.md
An extraneous blank line was introduced due to manual merge conflict editing.  This removes the blank line to correct formatting.
> Formatting: remove extraneous blank line

- model/Core/Classes/Bom.md
"Bill of Materials" is always written with "of" in the spec.
> Use consistent case.

- model/Core/Vocabularies/ProfileIdentifierType.md
- Remove non-existing `usage` profile (for 3.0, it got pushed to 3.1 see: #191)
- Add missing `lite` profile
- <s>Sort entries (will make it easier to spot anything missing in the future)</s>
This will fix #735 as reported by @vargenau
> Core: Update ProfileIdentifierType entries

- serialization/json_ld/validation.md
Adds a markdown file that explains how to manually validate SPDX 3 documents against the JSON schema and SHACL model
> Add document to describe how to validate documents

- serialization/json_ld/examples/agent1.json
- serialization/json_ld/examples/annotation1.json
- serialization/json_ld/examples/converted_from_spdx_2.json
- serialization/json_ld/examples/file1.json
- serialization/json_ld/examples/org1.json
- serialization/json_ld/examples/package1.json
- serialization/json_ld/examples/person1.json
- serialization/json_ld/examples/person2.json
- serialization/json_ld/examples/relationship1.json
- serialization/json_ld/examples/sbom1.json
- serialization/json_ld/examples/spdx_document1.json
- serialization/json_ld/examples/spdx_document2.json
- serialization/json_ld/examples/spdx_document3.json
- serialization/json_ld/examples/spdx_document4.json
- serialization/json_ld/examples/tool1.json
- serialization/json_ld/examples/two_sboms.json
The current examples in serializaiton/json_ld/examples are all except one invalid.
> fix all jsonld examples

- model/Core/Vocabularies/RelationshipType.md
This commit adds language to note the class constraints on security relationship types.
/cc @rnjudge 
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@stacklok.net>
> Relationships: Note class contraints on security types

- model/Core/Classes/NamespaceMap.md
The use of `1)` will not render correctly with MkDocs.
Should use `1.`
> Fix list in NamespaceMap

- model/AI/Classes/EnergyConsumption.md
- model/AI/Classes/EnergyConsumptionDescription.md
- model/AI/Properties/energyConsumption.md
Update descriptions for
- energyConsumption property of AIPackage
- Was mistakenly described as a "free-form text", which it is not.
- Remove a specific reference to "training", as this property can be used for more than just training
- EnergyConsumption class
- Add an example snippet
- EnergyConsumptionDescription class
- Add an example snippet
This will close #767 and close #771
Thanks @VenkatTechnologist for comments.
> AI: Energy consumption: Add examples and update desc

- model/Core/Vocabularies/RelationshipType.md
Change from:
```text
The `from` Element has been trained by the `to` Element(s)
```
to:
```text
The `from` Element has been trained on the `to` Element(s)
```
- This will make the description consistent to the name of the type.
- `testedOn` type description also use the phrase "tested on"
- Also to avoid confusion. "by" may signify that the `to` is an Agent, which is not the case here.
> trainedOn relationship type desc: "trained by" -> "trained on"

- model/Security/Vocabularies/CvssSeverityType.md
"low" entry should be for 0.1-3.9 range of CVSS score, not 0-3.9.
Current:
```markdown
- critical: When a CVSS score is between 9.0 - 10.0
- high: When a CVSS score is between 7.0 - 8.9
- medium: When a CVSS score is between 4 - 6.9
- low: When a CVSS score is between 0 - 3.9
- none: When a CVSS score is 0
```
Proposed fix:
```markdown
- critical: When a CVSS score is between 9.0 - 10.0
- high: When a CVSS score is between 7.0 - 8.9
- medium: When a CVSS score is between 4.0 - 6.9
- low: When a CVSS score is between 0.1 - 3.9
- none: When a CVSS score is 0.0
```
Refs:
- https://www.first.org/cvss/v3.0/specification-document#Qualitative-Severity-Rating-Scale
- https://www.first.org/cvss/v4.0/specification-document#Qualitative-Severity-Rating-Scale
> Fix "low" entry of CvssSeverityType

- Glossary.md
That was suggested in a comment in https://github.com/spdx/spdx-spec/pull/954
> Add SPDX in glossary as its meaning has changed between SPDX 2 and 3

- model/AI/Classes/AIPackage.md
- model/Dataset/Classes/DatasetPackage.md
- model/Security/Classes/VulnAssessmentRelationship.md
Now that spec-parser processes and check external property restrictions, the following warnings were generated:
> WARNING: In class `/AI/AIPackage` property `/Core/Artifact/releaseTime` has same `maxCount` as the parent class
> WARNING: In class `/AI/AIPackage` property `/Core/Artifact/suppliedBy` has same `maxCount` as the parent class
> WARNING: In class `/AI/AIPackage` property `/Software/Package/downloadLocation` has same `maxCount` as the parent class
> WARNING: In class `/AI/AIPackage` property `/Software/Package/packageVersion` has same `maxCount` as the parent class
> WARNING: In class `/AI/AIPackage` property `/Software/SoftwareArtifact/primaryPurpose` has same `maxCount` as the parent class
> WARNING: In class `/Dataset/DatasetPackage` property `/Core/Artifact/builtTime` has …
> Remove unnecessary restrictions

- model/Security/Classes/EpssVulnAssessmentRelationship.md
Fix spec-parser's "has same maxCount as the parent class" warning.
In class /Security/EpssVulnAssessmentRelationship, property /Security/VulnAssessmentRelationship/publishedTime has same maxCount as the parent class.
> Remove redundant maxCount of EpssVulnAssessmentRelationship

- README.md
- model/AI/AI.md
- model/Build/Build.md
- model/Core/Core.md
- model/Dataset/Dataset.md
- model/ExpandedLicensing/ExpandedLicensing.md
- model/ExpandedLicensing/Individuals/NoAssertionLicense.md
- model/ExpandedLicensing/Individuals/NoneLicense.md
- model/Extension/Extension.md
- model/Licensing/Licensing.md
- model/Lite/Lite.md
- model/Security/Security.md
- model/SimpleLicensing/SimpleLicensing.md
- model/Software/Software.md
This updates the URIs of the model terms to refer to 3.0.1.
As decided in the tech call of 16 July 2024.
> Change URIs to 3.0.1

- model/Core/Datatypes/MediaType.md
- model/Core/Properties/packageVerificationCodeExcludedFile.md
- model/Core/Vocabularies/ExternalRefType.md
- model/Core/Vocabularies/HashAlgorithm.md
Update refs in MediaType, packageVerificationCodeExcludedFile, ExternalRefType, HashAlgorithm
- Add text labels to bare URLs, as they are required by OMG/ISO standard documents.
- Add ref links to Bower, Maven, npm, NuGet packages. Using [information from v2.3](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/#f3-package-manager).
- These links are already in Normative References chapter of the spec, but missing from v3.0 model file.
- Standardized IETF RFC links -- see: https://github.com/spdx/spdx-spec/issues/1012
- Update obsoleted spec documents:
- sha224: replace pre-RFC (Internet Draft) ref with RFC 3874
- sha256, sha384, sha51: replace obsoleted refs RFC 4634 with RFC 6234
This PR will also supersede small part of #751
> [Core] Add text labels to bare URLs

- model/Build/Classes/Build.md
In the [Build](https://github.com/spdx/spdx-3-model/blob/main/model/Build/Classes/Build.md) class description, a reference to "SLSA provenance" contains no version or date information.
> Definitions of "buildType", "configSourceEntrypoint", "configSourceUri",
"parameters" and "environment" follow those defined in
[SLSA provenance](https://slsa.dev/provenance/v0.2).
The "SLSA provenance" text links to https://slsa.dev/provenance/v0.2
This PR add "v0.2" to the text, to match the version in the URL.
This is also to make it explicit in the text about the desired version, which is necessary because:
- Normative References section states that:
> For undated references, the latest edition of the referenced document (including any amendments) applies.
- The latest version of SLSA is 1.0 …
> [Build] Specify v0.2 version number for SLSA Provenance

- model/ExpandedLicensing/Classes/CustomLicense.md
- model/ExpandedLicensing/Classes/CustomLicenseAddition.md
- model/ExpandedLicensing/Classes/LicenseAddition.md
- model/ExpandedLicensing/Classes/ListedLicense.md
- model/ExpandedLicensing/Classes/ListedLicenseException.md
- model/ExpandedLicensing/Classes/WithAdditionOperator.md
- model/ExpandedLicensing/Properties/deprecatedVersion.md
- model/ExpandedLicensing/Properties/isDeprecatedAdditionId.md
- model/ExpandedLicensing/Properties/isFsfLibre.md
- model/ExpandedLicensing/Properties/isOsiApproved.md
- model/ExpandedLicensing/Properties/licenseXml.md
- model/SimpleLicensing/Classes/AnyLicenseInfo.md
- model/SimpleLicensing/Classes/SimpleLicensingText.md
- model/SimpleLicensing/Properties/customIdToUri.md
Add text labels to bare URLs in ExpandedLicensing and SimpleLicensing Profiles.
For the purpose of OMG/ISO standard doc preparation.
This PR will also supersede large parts of #751
> [Licensing] Add text labels to bare URLs

- model/Core/Vocabularies/RelationshipType.md
- Fix typo in hasAddedFile: "is is" -> "is"
- Fix typo in type name: "hasPrerequsite" -> "hasPrerequisite"
- Make fullstops and commas in of all types in RelationshipType consistent.
- some "during a LifecycleScopeType period" have comman before it, some don't
- some description with one sentence have fullstop, some don't
> Fix typos: hasPrerequsite -> hasPrerequisite, and others

- model/ExpandedLicensing/Properties/licenseXml.md
- Link to v3.24.0 of license-list-XML
- Use "SPDX License List XML Schema" name, for ref text label, taken from a heading in [schema/ListedLicense.xsd](https://github.com/spdx/license-list-XML/blob/v3.24.0/schema/ListedLicense.xsd)
- `<xhtml:h1>SPDX License List XML Schema</xhtml:h1>`
> licenseXml: Link license-list-XML to a specific version (v3.24.0)

- model/ExpandedLicensing/Properties/additionText.md
- model/ExpandedLicensing/Properties/standardAdditionTemplate.md
- model/ExpandedLicensing/Properties/standardLicenseTemplate.md
- model/SimpleLicensing/Properties/licenseText.md
This PR addresses two ExpandedLicensing properties at using Legacy Text Template:
- standardAdditionTemplate
- standardLicenseTemplate
See discussion at https://github.com/spdx/spdx-3-model/issues/747#issuecomment-2263645277
> Recommend to use licenseXml, instead of Legacy Text Template properties

- model/Core/Classes/PackageVerificationCode.md
PackageVerificationCode has various indent sizes in the pseudo code section,
make them even for better readability.
Also add a space between characters in sort order list for readability.
> Make pseudocode indents even - PackageVerificationCode

- model/Core/Classes/NamespaceMap.md
The CI for the SPDX spec is currently failing with the warning "WARNING -  Doc file 'model/Core/Classes/NamespaceMap.md' contains a link '../../../docs/serializations.md', but the target 'docs/serializations.md' is not found among documentation files."  It looks like the published spec has the serializations published at the root level, not in the docs folder.
> Fix link to serialization

- model/Core/Vocabularies/HashAlgorithm.md
Adler32 was added to SPDX 2.3 based on issue 624 (https://github.com/spdx/spdx-spec/issues/624).  This algorithm is not present in the SPDX 3.0 spec.
I searched the SPDX tech minutes to see if this was discussed for 3.0 and I could not find any record - so I assume this was an oversight.
> Add Adler32 to hash algorithms

- serialization/README.md
From
```markdown
`SpdxDocument` with `NamespaceMap
```
to
```markdown
`SpdxDocument` with `NamespaceMap`
```
> Add 1 missing closing ` for NamespaceMap in serialization/README

- model/ExpandedLicensing/Classes/ConjunctiveLicenseSet.md
- model/ExpandedLicensing/ExpandedLicensing.md
- model/Licensing/Licensing.md
- model/SimpleLicensing/Classes/AnyLicenseInfo.md
- model/SimpleLicensing/Classes/LicenseExpression.md
- model/SimpleLicensing/Properties/customIdToUri.md
- model/SimpleLicensing/Properties/licenseExpression.md
- model/SimpleLicensing/SimpleLicensing.md
To fix warnings in https://github.com/spdx/spdx-spec/pull/1052
> Lowercasing all filename ref to spdx-spec

- model/Core/Classes/PackageVerificationCode.md
Add back in line separators, else the sort won't work. 
Use revised property names.   Set default value for hashValue.
Signed-off-by:  Kate Stewart <kstewart@linuxfoundation.org>
> Revert PackageVerificationCode.md to original algorithm, and improve readability/formatting.

- model/Core/Properties/relationshipType.md
- model/Core/Vocabularies/RelationshipType.md
Use actual spelling of the Class
> SPDXDocument -> SpdxDocument

- CHANGELOG.md
- model/Build/Build.md
- model/Core/Vocabularies/RelationshipType.md
Made the RelationshipType singular:
- hasInputs -> hasInput
- hasOutputs -> hasOutput
All other "has" relationship types have a singular "target".
For example, hasAddedFile, hasDataFile, hasDependencyManifest, hasDynamicLink.
> RelationshipType: hasInputs/hasOutputs -> hasInput/hasOutput

- model/Core/Vocabularies/RelationshipType.md
- One instance of "each `to` Elements" -> "each `to` Element"
- One instance of "each Element `to`" -> "each `to` Element"
- One instance of "each of the `to` Element(s)" -> "each `to` Element"
Make them the same as other 25+ instances of "each `to` Element"
- "Software Artifact" ->  "SoftwareArtifact", to match class name spelling
> Standardize phrase "each to Element" in RelationshipType

- model/Build/Classes/Build.md
Update Build.md to remove separate definition of properties where it was referencing SLSA v0.2, and to avoid confusion against already defined properties.
@nishakm @JPEWdev
> Update Build.md to remove separate definition of properties

- model/ExpandedLicensing/Properties/licenseXml.md
Update SPDX License List link to [v3.25.0](https://github.com/spdx/license-list-XML/releases/tag/v3.25.0)
- Similar PR in spdx-spec: https://github.com/spdx/spdx-spec/pull/1075
> Update SPDX License List link to v3.25.0

- model/Build/Properties/parameter.md
- model/Extension/Classes/CdxPropertiesExtension.md
- model/Extension/Classes/CdxPropertyEntry.md
- model/Extension/Properties/cdxPropName.md
- model/Extension/Properties/cdxPropValue.md
- model/Extension/Properties/cdxProperty.md
- model/SimpleLicensing/Classes/AnyLicenseInfo.md
- model/SimpleLicensing/Classes/LicenseExpression.md
- model/SimpleLicensing/Properties/licenseExpression.md
Found during diagrams check.
- Format "parameter" description to make it parallel with "environment" description, as both of them are related and their desc referring to each other.
- Fix typo in LicenseExpression and licenseExpression
- The "licenseExpression string" is referring to a property "licenseExpression" of a class "LicenseExpression". Lowercase "l" should be used for "licenseExpression string".
- Removing the Annex number. Make that section of text similar in both class and property.
- AnyLicenseInfo: Add link to NonLicense and NoAssertionLicense (other classes already have link)
- Update descriptions of classes and properties related to CdxPropertiesExtension
- Were refer to non-existing `CdxExtension` and `cdxProperties`
- CdxPropertiesExtension
- CdxPropertyEntry
- …
> Fix model desc inconsistencies; CdxPropertiesExtension mention non-existing class/property

- model/Core/Classes/ExternalMap.md
- model/Core/Properties/externalSpdxId.md
In [ExternalMap](https://spdx.github.io/spdx-spec/v3.0.1-draft/model/Core/Classes/ExternalMap/) and [externalSpdxId](https://spdx.github.io/spdx-spec/v3.0.1-draft/model/Core/Properties/externalSpdxId/) description,
replacing the "Document" (uppercase "D") with "SpdxDocument".
To resolve #871
> ExternalMap: Replace "Document" with "SpdxDocument"

- model/Lite/Lite.md
The last two lists in https://spdx.github.io/spdx-spec/v3.0.1/model/Lite/Lite/ (starts at "For a /Core/SpdxDocument"...) don't rendered correctly.
This PR adds a newline before the lists, to make it render correctly.
Also fixes property name mincount to minCount.
> Lite: Fix conformance lists rendering; mincount -> minCount

- model/Build/Properties/configSourceEntrypoint.md
- model/Core/Classes/ElementCollection.md
- model/Core/Datatypes/MediaType.md
- model/Security/Properties/catalogType.md
- model/Security/Properties/decisionType.md
- model/Security/Properties/vectorString.md
- serialization/README.md
- With the keywords inside, the configuration in YAML looks like one that similar to GitHub workflow.
- This PR gives the configuration an indentation according to those keywords, checked with GitHub web editor.
- Replace mentions of `ExploitCatalogType.md` and `SsvcDecisionType.md` Markdown files (which are not visible to readers, as `.md` part will be removed when site/PDF got generated) with actual links to the vocabularies.
- Replace 2 instances of `**Constraints**` with `*Constraints*`, to make them similar to other Constraints instances
- in MediaType: change `**Examples**` to `*Example*` to make it similar to other Example instances
- Update serialization/README, was referenced to an outdated name `*Syntax*`. It is now `*Example*`.
> Remove mentions of .md; fix indent in YAML example; fix heading consistency

- model/Build/Properties/buildType.md
A follow up of #875 that we just merged an hour ago - the rendering of the new bullet list in the description is broken.
See: https://spdx.github.io/spdx-spec/v3.0.1/model/Build/Properties/buildType/
This PR just fix that.
> buildType: Fix broken bullet lists rendering

- model/Core/Individuals/SpdxOrganization.md
- This PR should be reviewed alongside https://github.com/spdx/spec-parser/pull/154
- Add a named individual: `SpdxOrganization`
- This individual is meant to be used for CreationInfo inside named individuals
- <s>Note that currently "## Property Values" is not processed, another PR in spec-parser is needed for spdxId, etc to be included in SpdxOrganization - see: https://github.com/spdx/spec-parser/pull/155</s>
> Add /Core/Individuals/SpdxOrganization

- Glossary.md
- model/Build/Build.md
- model/Build/Properties/buildType.md
- model/Core/Properties/dataLicense.md
- model/Core/Properties/externalSpdxId.md
- model/Core/Properties/hashValue.md
- model/Core/Properties/import.md
- model/Core/Properties/originatedBy.md
- model/Core/Properties/spdxId.md
- model/Core/Properties/verifiedUsing.md
- model/Core/Vocabularies/AnnotationType.md
- model/Core/Vocabularies/ExternalIdentifierType.md
- model/Core/Vocabularies/RelationshipType.md
- model/Security/Properties/impactStatement.md
- model/Software/Properties/additionalPurpose.md
- model/Software/Properties/sourceInfo.md
- model/Software/Vocabularies/SoftwarePurpose.md
- Fix typos in model descriptions
- Make sure that the property names have correct casing (starts with a lowercase letter) in model descriptions
- "ExternalSpdxId identifies ..." --> "An externalSpdxId identifies ..."
- Add "The" to entry description of SoftwarePurpose vocab (some already have, some don't; also make "The" casing consistent with entry description in other vocabs)
- "Element ..." --> "The Element ..."
> Fix typos, casing, and make SoftwarePurpose entry description consistent

- CHANGELOG.md
- model/Core/Individuals/SpdxOrganization.md
Update the change log with changes from
- #875
- #880
- #815
- #741
> [CHANGELOG] Add changes in buildType and SpdxOrganization

- model/Security/Classes/VexVulnAssessmentRelationship.md
In VexVulnAssessmentRelationship class:
- "Asbtract" -> "Abstract"
- Also fix inconsistent use of emphasis markup (`_,,,_` -> `*...*`) (the rest of the model files use `*...*`)
> Fix typo: Asbtract -> Abstract

- model/AI/AI.md
- model/Core/Datatypes/MediaType.md
- model/Core/Individuals/NoAssertionElement.md
- model/Core/Individuals/NoneElement.md
- model/Dataset/Dataset.md
- model/Licensing/Licensing.md
- model/Lite/Lite.md
- an /SimpleLicensing/AnyLicenseInfo -> a /SimpleLicensing/AnyLicenseInfo
- specificiation -> specification
- descendents -> descendants
> Fix typos: an -> a; descendents -> descendants

- model/Core/Individuals/NoneElement.md
As reported by ilan during 12 Nov 2024 Tech meeting
> Fix typo: NoneLicenseElement -> NoneElement

- model/Core/Properties/packageVerificationCodeExcludedFile.md
Require filenames to use the relative path syntax.
To fix https://github.com/spdx/spdx-3-model/issues/910
> use relative path syntax

- model/Security/Classes/VexAffectedVulnAssessmentRelationship.md
- /Security/actionStatement:
The description in actionStatement states that:
"When an element is referenced with a VexAffectedVulnAssessmentRelationship, the relationship MUST include one actionStatement that SHOULD describe actions to remediate or mitigate the vulnerability".
This conforms to VEX_Use_Cases_Aprill2022:
"If a status is AFFECTED, the VEX document must have an action statement that tells the product user what to do".
The cardinality of actionStatement in VexAffectedVulnAssessmentRelationship is 0..1 but should to be 1..1.
- /Security/actionStatementTime:
It is optional and records the time when the actionStatement was first communicated (this conforms to the VEX docs).
The cardinality of actionStatementTime in VexAffectedVulnAssessmentRelationship is 0..* but should to be …
> VEX affected cardinalities

- model/Core/Classes/IndividualElement.md
- model/Core/Individuals/NoAssertionElement.md
- model/Core/Individuals/NoneElement.md
This will allow individuals to be of a type that can be instantiated and could resolve the issue with SHACL validation failing https://github.com/spdx/spec-parser/issues/165
> Create an IndividualElement class

- model/Build/Build.md
- model/Core/Classes/ElementCollection.md
- model/Core/Properties/profileConformance.md
- model/Core/Vocabularies/ProfileIdentifierType.md
- model/Licensing/Licensing.md
There are some remaining instances that the profile names are not in capitalised (first letter is uppercase) format. This PR updates them:
- core -> Core (when mentioned the profile name)
- core -> "core" (when mentioned the entry from ProfileIdentifierType, used in profileConformance property)
> Capitalise Profile names
